package cn.itcast.domain;
// Generated 2018-4-19 13:48:25 by Hibernate Tools 3.6.0.Final

/**
 * Region generated by hbm2java
 */
public class Region implements java.io.Serializable {

	private static final long serialVersionUID = -8343812555231239716L;
	
	private double regionId;
	private String regionCode;
	private String regionName;
	private double parentId;
	private double regionLevel;
	private double regionOrder;
	private String regionNameEn;
	private String regionShortnameEn;

	public Region() {
	}

	public Region(double regionId, String regionCode, String regionName, double parentId, double regionLevel,
			double regionOrder, String regionNameEn, String regionShortnameEn) {
		this.regionId = regionId;
		this.regionCode = regionCode;
		this.regionName = regionName;
		this.parentId = parentId;
		this.regionLevel = regionLevel;
		this.regionOrder = regionOrder;
		this.regionNameEn = regionNameEn;
		this.regionShortnameEn = regionShortnameEn;
	}

	public double getRegionId() {
		return this.regionId;
	}

	public void setRegionId(double regionId) {
		this.regionId = regionId;
	}

	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	public double getParentId() {
		return this.parentId;
	}

	public void setParentId(double parentId) {
		this.parentId = parentId;
	}

	public double getRegionLevel() {
		return this.regionLevel;
	}

	public void setRegionLevel(double regionLevel) {
		this.regionLevel = regionLevel;
	}

	public double getRegionOrder() {
		return this.regionOrder;
	}

	public void setRegionOrder(double regionOrder) {
		this.regionOrder = regionOrder;
	}

	public String getRegionNameEn() {
		return this.regionNameEn;
	}

	public void setRegionNameEn(String regionNameEn) {
		this.regionNameEn = regionNameEn;
	}

	public String getRegionShortnameEn() {
		return this.regionShortnameEn;
	}

	public void setRegionShortnameEn(String regionShortnameEn) {
		this.regionShortnameEn = regionShortnameEn;
	}

}
